import { describe, it, expect } from 'vitest'
import type { Transaction, TransactionInsert, TransactionUpdate } from '../transaction'

/**
 * Compile-time schema-drift canary (fix-plan 1.2).
 *
 * The fixtures below name every column of the `transactions` table exactly
 * as a real caller would — an INSERT payload and a full row read back.
 * TypeScript excess-property-checks object literals assigned to a typed
 * variable, so if a migration renames or drops a column in
 * `database.types.ts` (regenerated by `packages/shared/scripts/
 * gen-db-types.sh` whenever the schema changes) without this file being
 * updated to match, one of the two literals below either references a key
 * that no longer exists on the (regenerated) type — an excess-property
 * error — or omits one the type now requires. Either way this file stops
 * compiling.
 *
 * The actual protection is `tsc --noEmit`: the `typecheck` turbo task /
 * CI job, which — per `packages/shared/tsconfig.json`'s
 * `"include": ["src/**\/*"]` — type-checks test files too, not just
 * application code. The `expect()` calls below exist so `vitest run`
 * exercises the fixtures as more than dead code and this file also earns
 * its keep as a `turbo test` result; they are not where the guarantee
 * comes from. Try it: rename `transactions.amount` to `amount_cents` in
 * `database.types.ts` without touching this file, and `npm run
 * typecheck -w packages/shared` fails on this file.
 */
describe('database.types.ts — schema drift canary', () => {
  const insert: TransactionInsert = {
    id: 'a0000000-0000-0000-0000-000000000000',
    user_id: 'u0000000-0000-0000-0000-000000000000',
    amount: 12.5,
    direction: 'debit',
    currency_code: 'USD',
    category_id: null,
    merchant: 'Coffee Shop',
    merchant_domain: null,
    note: null,
    payment_method: 'credit_card',
    amount_in_profile_currency: 12.5,
    fx_rate_to_profile: 1,
    fx_rate_date: '2026-08-08',
    transacted_at: '2026-08-08T12:00:00Z',
    source: 'manual',
    raw_transcript: null,
    ai_confidence: null,
    is_recurring: false,
    recurring_rule_id: null,
    recurring_frequency: null,
    client_id: 'c0000000-0000-0000-0000-000000000000',
    client_created_at: '2026-08-08T12:00:00Z',
    version: 1,
    is_deleted: false,
    deleted_at: null,
    synced_at: null,
  }

  const row: Transaction = {
    id: 'a0000000-0000-0000-0000-000000000000',
    user_id: 'u0000000-0000-0000-0000-000000000000',
    amount: 12.5,
    direction: 'debit',
    currency_code: 'USD',
    category_id: null,
    merchant: 'Coffee Shop',
    merchant_domain: null,
    note: null,
    payment_method: 'credit_card',
    amount_in_profile_currency: 12.5,
    fx_rate_to_profile: 1,
    fx_rate_date: '2026-08-08',
    transacted_at: '2026-08-08T12:00:00Z',
    source: 'manual',
    raw_transcript: null,
    ai_confidence: null,
    is_recurring: false,
    recurring_rule_id: null,
    recurring_frequency: null,
    client_id: 'c0000000-0000-0000-0000-000000000000',
    client_created_at: '2026-08-08T12:00:00Z',
    version: 1,
    is_deleted: false,
    deleted_at: null,
    synced_at: null,
    created_at: '2026-08-08T12:00:00Z',
    updated_at: '2026-08-08T12:00:00Z',
  }

  it('names every column of a real transactions INSERT payload', () => {
    expect(insert.amount).toBe(12.5)
    expect(insert.direction).toBe('debit')
    expect(Object.keys(insert).length).toBeGreaterThan(20)
  })

  it('names every column of a real transactions row', () => {
    expect(row.created_at).toBe('2026-08-08T12:00:00Z')
    expect(Object.keys(row).length).toBe(Object.keys(insert).length + 2) // + created_at, updated_at
  })

  it('an UPDATE payload can still narrow to one real column plus id', () => {
    // `insert.id` is `string | undefined` (the column has a DB default, so
    // it's optional on INSERT) even though this fixture happened to set
    // it — narrow it explicitly rather than widening `TransactionUpdate.id`
    // to match, which would just re-introduce the bug 1.2 exists to catch.
    const id = row.id
    const update: TransactionUpdate = { id, amount: 99 }
    expect(update.amount).toBe(99)
  })
})
