// Adopts the UIKit scene lifecycle, which iOS 27 requires (Oct 3 2026).
//
// What broke: on iOS 27, UIKit terminates at launch any app that has not
// adopted UIScene, with a deliberate trap in
// _UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption. Every
// Murmur launch on the owner's iPhone after it updated to iOS 27.0.1 died
// there (five crash reports pulled off the device, all identical, build 67).
// Neither Expo SDK 54's template nor React Native 0.81 adopts scenes: the
// generated AppDelegate builds a UIWindow in didFinishLaunching and starts
// React Native in it, and Info.plist has no UIApplicationSceneManifest.
//
// The fix, done here rather than in ios/ because ios/ is regenerated by
// prebuild on every EAS build:
//
//   1. Info.plist declares a single-window scene configuration whose
//      delegate is SceneDelegate.
//   2. AppDelegate keeps creating and binding the React Native factory
//      (Expo's module system hooks in there) but no longer builds a window.
//   3. SceneDelegate builds the window from the UIWindowScene and starts
//      React Native in it.
//
// The part that is easy to get wrong is deep links. Under scenes, iOS
// stops calling application(_:open:options:) and application(_:continue:)
// on the app delegate; URLs arrive at the scene delegate instead. Murmur
// depends on those URLs for sign-in (voiceexpense://auth/callback), the
// Shortcuts and Apple Pay capture path (voiceexpense://shortcut?...), and
// universal links. So SceneDelegate:
//
//   - rebuilds launchOptions from the scene's connection options, because
//     React Native's Linking.getInitialURL() reads the cold-start URL from
//     launchOptions[.url] and nowhere else, and
//   - forwards every URL and user activity back through the EXISTING
//     AppDelegate methods, which is exactly what iOS did before scenes (it
//     put the URL in launchOptions AND called open:options:). Every Expo
//     subscriber and RCTLinkingManager therefore sees what it always saw,
//     and nothing downstream needs to know scenes exist.
//
// SceneDelegate is appended to AppDelegate.swift rather than added as its
// own file: same target and module, so `$(PRODUCT_MODULE_NAME).SceneDelegate`
// resolves without touching the Xcode project's build phases.
//
// The plugin fails the prebuild loudly if the template code it edits has
// moved. A silent miss would produce either an app that starts React Native
// twice or one that never starts it, both of which ship as a blank screen.
const { withAppDelegate, withInfoPlist } = require('expo/config-plugins')

const MARKER = '// Murmur: UIScene lifecycle (plugins/withSceneLifecycle.js)'

// The window + start block of the SDK 54 AppDelegate template. Whitespace
// tolerant, nothing else.
const WINDOW_BLOCK =
  /#if os\(iOS\) \|\| os\(tvOS\)\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\s*factory\.startReactNative\(\s*withModuleName: "main",\s*in: window,\s*launchOptions: launchOptions\)\s*#endif/

const SCENE_DELEGATE = `
${MARKER}
//
// iOS 27 terminates apps that do not adopt the scene lifecycle. The window
// is built here, from the scene, instead of in AppDelegate. URLs and user
// activities are forwarded back through AppDelegate so everything that
// listened there before (Expo modules, RCTLinkingManager) still hears them.
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene,
          let appDelegate = UIApplication.shared.delegate as? AppDelegate,
          let factory = appDelegate.reactNativeFactory else { return }

    // React Native reads the cold-start URL from launchOptions only
    // (RCTLinkingManager getInitialURL). Under scenes it arrives in the
    // connection options, so it is carried across here.
    var launchOptions: [UIApplication.LaunchOptionsKey: Any] = [:]
    if let url = connectionOptions.urlContexts.first?.url {
      launchOptions[.url] = url
    }
    if let activity = connectionOptions.userActivities.first {
      launchOptions[.userActivityDictionary] = [
        "UIApplicationLaunchOptionsUserActivityKey": activity,
        "UIApplicationLaunchOptionsUserActivityTypeKey": activity.activityType,
      ]
    }

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    appDelegate.window = window
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions.isEmpty ? nil : launchOptions)

    // Before scenes, a URL launch put the URL in launchOptions AND called
    // application(_:open:options:). Doing both keeps that exact behaviour.
    if !connectionOptions.urlContexts.isEmpty {
      self.scene(scene, openURLContexts: connectionOptions.urlContexts)
    }
    for activity in connectionOptions.userActivities {
      self.scene(scene, continue: activity)
    }
  }

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else { return }
    for context in URLContexts {
      var options: [UIApplication.OpenURLOptionsKey: Any] = [:]
      if let source = context.options.sourceApplication { options[.sourceApplication] = source }
      if let annotation = context.options.annotation { options[.annotation] = annotation }
      options[.openInPlace] = context.options.openInPlace
      _ = appDelegate.application(UIApplication.shared, open: context.url, options: options)
    }
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else { return }
    _ = appDelegate.application(UIApplication.shared, continue: userActivity, restorationHandler: { _ in })
  }
}
`

function withSceneAppDelegate(config) {
  return withAppDelegate(config, (c) => {
    if (c.modResults.language !== 'swift') {
      throw new Error('withSceneLifecycle: expected a Swift AppDelegate, got ' + c.modResults.language)
    }
    let src = c.modResults.contents
    if (src.includes(MARKER)) return c // idempotent: prebuild without --clean re-runs mods

    if (!WINDOW_BLOCK.test(src)) {
      throw new Error(
        'withSceneLifecycle: the AppDelegate template no longer contains the window + startReactNative block ' +
          'this plugin replaces. Expo changed its template; update WINDOW_BLOCK before building, or iOS 27 ' +
          'launches will either never start React Native or start it twice.',
      )
    }
    src = src.replace(
      WINDOW_BLOCK,
      // The matched block starts at column 0 (it opens with #if), so the
      // replacement carries the method body's indent itself.
      '    // The window and React Native are started by SceneDelegate (iOS 27\n' +
        '    // requires the scene lifecycle). See plugins/withSceneLifecycle.js.',
    )
    c.modResults.contents = src.trimEnd() + '\n' + SCENE_DELEGATE
    return c
  })
}

function withSceneManifest(config) {
  return withInfoPlist(config, (c) => {
    c.modResults.UIApplicationSceneManifest = {
      // One window. Murmur is iPhone-only (supportsTablet: false) and has no
      // multi-window story to support.
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'Default Configuration',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SceneDelegate',
          },
        ],
      },
    }
    return c
  })
}

module.exports = function withSceneLifecycle(config) {
  return withSceneManifest(withSceneAppDelegate(config))
}
